backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "/public/admin/files/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/admin/files/uploads"
display_url: https://sfrr.org
# logo_url: https://sfrr.org/static/images/SFRRI-footer-logo.png
logo_url: http://localhost:3000/static/media/SFRRI-New-logo-no-mapx2.1cf49e61.png

collections:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog" # Used in the UI
  #   folder: "content/blog" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   extension: json
  #   format: json
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: 'news'
    label: 'News'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "News - Before Meetings"
        name: "before-meetings"
        file: "_data/news/before-meetings.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "Meetings"
        # label_singular: 'Meeting'
        name: "meetings"
        file: "_data/news/meetings.json"
        fields:
          - label: 'Meetings'
            label_singular: 'Meeting'
            name: 'meetings'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - { name: 'meeting_title', label: 'Meeting title' }
              - { name: 'date', label: 'Date' }
              - { name: 'location', label: 'Location', widget: "markdown" }
              - { name: 'further_information_link_text', label: 'Further information link text' , required: false }
              - { name: 'further_information_link_hypertext', label: 'Further information link hypertext', required: false }
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: false
                media_library:
                  config:
                    # max_file_size: 512000
                    multiple: true
              - {label: "Add to Related Meetings", name: "add_to_related_meetings", widget: "boolean", default: false}
      - label: "News - After Meetings"
        name: "after-meetings"
        file: "_data/news/after-meetings.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "News - In Memoriam"
        name: "in_memoriam"
        file: "_data/news/in-memoriam.json"
        fields:
          - label: 'News - In Memoriam'
            name: 'in_memoriam'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - { name: 'name', label: 'Name', widget: "markdown" }
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: false
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    max_file_size: 512000
                    multiple: true

  - name: 'society'
    label: 'Society'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:    
      - label: "Presidential Address"
        name: "presidential-address"
        file: "_data/society/presidential-address.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "SFRRI Executive"
        name: "sfrri-executive"
        file: "_data/society/sfrri-executive.json"
        fields:
          - label: 'SFRRI Executive Member'
            name: 'sfrri_executive_member'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: false
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    max_file_size: 512000
                    multiple: true
              - {label: "Title", name: "title"}
              - {label: "Name", name: "name"}
              - {label: "Bio", name: "bio", widget: "markdown"}
              - {label: "Address", name: "address", widget: "markdown"}
              - {label: "Contact details", name: "contact_details", widget: "markdown"}
      - label: "Past Presidents"
        name: "past-presidents"
        file: "_data/society/past-presidents.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true    
      - label: "History"
        name: "history"
        file: "_data/society/history.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "Governance & Byelaws"
        name: "governance-&-byelaws"
        file: "_data/society/governance-&-byelaws.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true    
      - label: "SFRRI Awards & Fellowships"
        name: "sfrri-awards-&-fellowships"
        file: "_data/society/sfrri-awards-&-fellowships.json"
        fields:
          - {label: "Body column 1", name: "body_col1", widget: "markdown"}
          - {label: "Body column 2", name: "body_col2", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "Women In Science Forum"
        name: "women-in-science-forum"
        file: "_data/society/women-in-science-forum.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
      - label: "Obituaries"
        name: "obituaries"
        file: "_data/society/obituaries.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true
                

  - name: 'sfrr-societies'
    label: 'SFRR Societies'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "SFRR Societies"
        name: "sfrr-societies"
        file: "_data/sfrr-societies.json"
        fields:
          - label: 'SFRR Society'
            name: 'sfrr_society'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - {label: "Name", name: "name"}
              - {label: "Link", name: "link"}
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: true
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    max_file_size: 512000
                    multiple: true
              - {label: "Affiliated Society", name: "affiliated_society", widget: "boolean", default: false}

  - name: 'membership'
    label: 'Membership'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Membership"
        name: "membership"
        file: "_data/membership.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true     

  - name: 'conferences'
    label: 'Conferences'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Future SFRRI Conferences"
        name: "future-sfrri-conferences"
        file: "_data/conferences/future-sfrri-conferences.json"
        fields:
          - label: 'Future SFRRI Conferences'
            name: 'future_sfrri_conferences'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - { name: 'meeting_title', label: 'Meeting title' }
              - { name: 'date', label: 'Date' }
              - { name: 'location', label: 'Location', widget: "markdown" }
              - { name: 'further_information_link_text', label: 'Further information link text', required: false }
              - { name: 'further_information_link_hypertext', label: 'Further information link hypertext', required: false }
              # - { name: 'state_percentage' }
              # - {label: "Body", name: "body", widget: "markdown"}
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: false
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    # max_file_size: 512000
                    multiple: true
      - label: "Past SFRRI Related Conferences"
        name: "sfrri-related-conferences"
        file: "_data/conferences/sfrri-related-conferences.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true     
        # fields:
        #   - label: 'SFRRI Related Conferences'
        #     name: 'future_sfrri_conferences'
            # widget: 'list'
            # allow_add: true
            # collapsed: true
            # fields:
            #   - { name: 'meeting_title', label: 'Meeting title' }
            #   - { name: 'date', label: 'Date' }
            #   - { name: 'location', label: 'Location', widget: "markdown" }
            #   - { name: 'further_information_link_text', label: 'Further information link text', required: false }
            #   - { name: 'further_information_link_hypertext', label: 'Further information link hypertext', required: false }
            #   # - {label: "Body", name: "body", widget: "markdown"}
            #   - label: "Upload File"
            #     name: "upload_path"
            #     widget: "file"
            #     required: false
            #     # default: "/admin/files/uploads"
            #     media_library:
            #       config:
            #         # max_file_size: 512000
            #         multiple: true
      - label: "Past SFRRI Conferences"
        name: "past-sfrri-conferences"
        file: "_data/conferences/past-sfrri-conferences.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true       
      - label: "Rules for Conference Organisation"
        name: "rules-for-conference-organisation"
        file: "_data/conferences/rules-for-conference-organisation.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true

  - name: 'forthcoming-related-meetings'
    label: 'Forthcoming Related Meetings'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Forthcoming Related Meetings"
        name: "forthcoming-related-meetings"
        file: "_data/related-meetings.json"
        fields:
          - label: 'Forthcoming Related Meetings'
            name: 'future_sfrri_conferences'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - { name: 'meeting_title', label: 'Meeting title' }
              - { name: 'date', label: 'Date' }
              - { name: 'location', label: 'Location', widget: "markdown" }
              - { name: 'further_information_link_text', label: 'Further information link text', required: false }
              - { name: 'further_information_link_hypertext', label: 'Further information link hypertext', required: false }
              # - { name: 'state_percentage' }
              # - {label: "Body", name: "body", widget: "markdown"}
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: false
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    # max_file_size: 512000
                    multiple: true

  - name: 'sfrri-outreach'
    label: 'SFRRI Outreach'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "SFRRI Outreach"
        name: "sfrri_outreach"
        file: "_data/sfrri-outreach.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true

  - name: 'journals'
    label: 'Journals'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Journals"
        name: "journals"
        file: "_data/journals.json"
        fields:
          - label: 'Journal'
            name: 'journal'
            widget: 'list'
            allow_add: true
            collapsed: true
            fields:
              - {label: "Name", name: "name"}
              - {label: "Link", name: "link"}
              - label: "Upload File"
                name: "upload_path"
                widget: "file"
                required: true
                # default: "/admin/files/uploads"
                media_library:
                  config:
                    max_file_size: 512000
                    multiple: false
              - {label: "Body", name: "body", widget: "markdown"}

  - name: 'education'
    label: 'Education'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Education"
        name: "education"
        file: "_data/education.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true    

  - name: 'contact'
    label: 'Contact'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Contact"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true 

  - name: 'careers & training'
    label: 'Careers & Training'
    # label_singular: 'Meeting'
    extension: json
    format: json
    create: false
    editor:
      preview: true
    files:      
      - label: "Careers & Training"
        name: "careers_&_training"
        file: "_data/careers-&-training.json"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Upload File"
            name: "upload_path"
            widget: "file"
            required: false
            # default: "/admin/files/uploads"
            media_library:
              config:
                # max_file_size: 512000
                multiple: true 

